# Generated by Django 5.0.1 on 2024-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='book_value_of_equity_per_share',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='discounted_tv',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='enterprise_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='equity_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='intrinsic_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='model',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='terminal_value',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='weighted_average_cost_of_capital',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
