# Generated by Django 5.0.1 on 2024-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_book_value_of_equity_per_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='cost_of_equity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='return_on_equity',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
