# Generated by Django 5.0.1 on 2024-03-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_cost_of_equity_stock_return_on_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='discounted_excess_returns',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
