# Generated by Django 5.0.1 on 2024-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stock_discounted_excess_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='growth',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
    ]
